net:
    in_channels: 20
    depth: 1
    lr: 0.0001
    dropout: False
    skip: False
    batchnorm: True
    is_refine: True
    norm_type: "minmax_constant"
    norm_dim: [ 0 ]


pose_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/pose.pt"
attr_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/attribute.pt"

data:
    - dataset:
             attr_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/train_attr.pt"
             ldm_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/train_landmarks.npy"
             id_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/id.pt"
             id_landmark_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/id_landmark.npy"
             augmentation: True

val:
    attr_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/val_attr.pt"
    ldm_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/val_landmarks.npy"
    id_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/id.pt"
    id_landmark_path: "/data1/chenlong/online_model_set/speed_data/datasets/man3_w_speed_val_6/id_landmark.npy"

optim:
    step: 150
    gamma: 0.5

batchsize: 128
epochs: 450
show_internal: 100
save_internal: 5


